### ISSUE TITLE
docker storagenode fails with SIGBUS

### ISSUE THREAD

**Issue by Hoeze** [storj/storj#1887]
I just tried running my first storagenode:
```
unexpected fault address 0x7f66e30a3000
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7f66e30a3000 pc=0xa9dd64]

goroutine 1 [running]:
runtime.throw(0xe13e28, 0x5)
        /usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc0001d50c8 sp=0xc0001d5098 pc=0x431a62
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:387 +0x47e fp=0xc0001d50f8 sp=0xc0001d50c8 pc=0x4471be
github.com/boltdb/bolt.(*DB).page(...)
        /go/pkg/mod/github.com/boltdb/bolt@v1.3.1/db.go:796
github.com/boltdb/bolt.(*DB).mmap(0xc000344000, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/boltdb/bolt@v1.3.1/db.go:282 +0x334 fp=0xc0001d51a0 sp=0xc0001d50f8 pc=0xa9dd64
github.com/boltdb/bolt.Open(0xc00019e7d0, 0xf, 0x180, 0xc0001d52a8, 0xc000167ac0, 0xc000167aa0, 0x0)
        /go/pkg/mod/github.com/boltdb/bolt@v1.3.1/db.go:230 +0x277 fp=0xc0001d5240 sp=0xc0001d51a0 pc=0xa9d657
storj.io/storj/storage/boltdb.NewShared(0xc00019e7d0, 0xf, 0xc0001d53e0, 0x2, 0x2, 0x7, 0xc00019e930, 0xe, 0xe1ad80, 0xd)
        /go/src/storj.io/storj/storage/boltdb/client.go:66 +0x82 fp=0xc0001d5360 sp=0xc0001d5240 pc=0xaabe02
storj.io/storj/storagenode/storagenodedb.New(0xc00015e4e0, 0xc00019e930, 0xe, 0xc00015ac80, 0x1c, 0xc00015aca0, 0x16, 0xc00019e7d0, 0xf, 0xc00019e930, ...)
        /go/src/storj.io/storj/storagenode/storagenodedb/database.go:65 +0x16b fp=0xc0001d5410 sp=0xc0001d5360 pc=0xb7644b
main.cmdRun(0x17b91e0, 0xc0002560e0, 0x0, 0xe, 0x0, 0x0)
        /go/src/storj.io/storj/cmd/storagenode/main.go:133 +0x3aa fp=0xc0001d57d0 sp=0xc0001d5410 pc=0xb816da
storj.io/storj/pkg/process.cleanup.func1.2(0xf4ce00, 0xc000254780)
        /go/src/storj.io/storj/pkg/process/exec_conf.go:252 +0x103 fp=0xc0001d5830 sp=0xc0001d57d0 pc=0xb00f63
storj.io/storj/pkg/process.cleanup.func1(0x17b91e0, 0xc0002560e0, 0x0, 0xe, 0x0, 0x0)
        /go/src/storj.io/storj/pkg/process/exec_conf.go:266 +0x1436 fp=0xc0001d5d78 sp=0xc0001d5830 pc=0xb02406
github.com/spf13/cobra.(*Command).execute(0x17b91e0, 0xc000256000, 0xe, 0xe, 0x17b91e0, 0xc000256000)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0x465 fp=0xc0001d5e60 sp=0xc0001d5d78 pc=0x615bf5
github.com/spf13/cobra.(*Command).ExecuteC(0x17b8f80, 0xc00007e180, 0x1, 0x1)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ec fp=0xc0001d5f30 sp=0xc0001d5e60 pc=0x61668c
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
storj.io/storj/pkg/process.Exec(0x17b8f80)
        /go/src/storj.io/storj/pkg/process/exec_conf.go:56 +0x180 fp=0xc0001d5f80 sp=0xc0001d5f30 pc=0xafedb0
main.main()
        /go/src/storj.io/storj/cmd/storagenode/main.go:323 +0x2d fp=0xc0001d5f98 sp=0xc0001d5f80 pc=0xb831bd
runtime.main()
        /usr/local/go/src/runtime/proc.go:200 +0x20c fp=0xc0001d5fe0 sp=0xc0001d5f98 pc=0x4333cc
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc0001d5fe8 sp=0xc0001d5fe0 pc=0x4610e1

goroutine 20 [chan receive]:
storj.io/storj/pkg/process.Ctx.func1(0xc0002c8540, 0xc0002d21f0)
        /go/src/storj.io/storj/pkg/process/exec_conf.go:141 +0x41
created by storj.io/storj/pkg/process.Ctx
        /go/src/storj.io/storj/pkg/process/exec_conf.go:140 +0x179

goroutine 21 [select]:
database/sql.(*DB).connectionOpener(0xc00032a0c0, 0xf4cb00, 0xc000168380)
        /usr/local/go/src/database/sql/sql.go:1000 +0xe8
created by database/sql.OpenDB
        /usr/local/go/src/database/sql/sql.go:670 +0x15e

goroutine 34 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 50 [IO wait]:
internal/poll.runtime_pollWait(0x7f66e3291ea8, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc0001ec918, 0x72, 0x0, 0x0, 0xe15df0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc0001ec900, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:384 +0x1ba
net.(*netFD).accept(0xc0001ec900, 0xc000042500, 0xc000088000, 0x7f66e56546d0)
        /usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc00019a370, 0xc000060d98, 0x410988, 0x30)
        /usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc00019a370, 0xd983a0, 0xc000200180, 0xcfef20, 0x17ad0b0)
        /usr/local/go/src/net/tcpsock.go:260 +0x48
net/http.(*Server).Serve(0xc0001a44e0, 0xf48f80, 0xc00019a370, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2859 +0x22d
storj.io/storj/pkg/process.initDebug.func2(0xc0002c8360, 0xf48f80, 0xc00019a370, 0xc0001e8c40)
        /go/src/storj.io/storj/pkg/process/debug.go:49 +0x15d
created by storj.io/storj/pkg/process.initDebug
        /go/src/storj.io/storj/pkg/process/debug.go:47 +0x337

goroutine 22 [select]:
database/sql.(*DB).connectionResetter(0xc00032a0c0, 0xf4cb00, 0xc000168380)
        /usr/local/go/src/database/sql/sql.go:1013 +0xfb
created by database/sql.OpenDB
        /usr/local/go/src/database/sql/sql.go:671 +0x194

goroutine 23 [select]:
database/sql.(*DB).connectionOpener(0xc00032a180, 0xf4cb00, 0xc0001683c0)
        /usr/local/go/src/database/sql/sql.go:1000 +0xe8
created by database/sql.OpenDB
        /usr/local/go/src/database/sql/sql.go:670 +0x15e

goroutine 24 [select]:
database/sql.(*DB).connectionResetter(0xc00032a180, 0xf4cb00, 0xc0001683c0)
        /usr/local/go/src/database/sql/sql.go:1013 +0xfb
created by database/sql.OpenDB
        /usr/local/go/src/database/sql/sql.go:671 +0x194
```
I started it with /app/config pointing to an empty folder.

**Comment by aligeti** [comment]
HI Hoeze 

what is your operating system you are trying to run the storagenode on? Please see us in 
https://community.storj.io. we can help you faster there. We need to know what is your initial setup information.

**Comment by Hoeze** [comment]
The problem was using storj on a fuse mount which does not support file growth.
I'm now testing withoute fuse, but it would be cool if storj would also suppport such types of file systems.

**Comment by ifraixedes** [comment]
@Hoeze thanks for the feedback.

It looks that the issues comes from BoltDB and for now it's the only backend that StorageNode supports.

My understanding is that BoltDB requires the file growth, but I cannot state that BolbDB can work on FUSE.
