### ISSUE TITLE
Looping after following startup guide

### ISSUE THREAD

**Issue by kdavis** [storj/storj#3073]
Followed the Startup documentation here. https://documentation.storj.io/setup/software-updates

```
2019-09-18T10:36:35.789Z	[34mINFO[0m	Configuration loaded from: /app/config/config.yaml
2019-09-18T10:36:35.801Z	[34mINFO[0m	Operator email: ********@****.com
2019-09-18T10:36:35.801Z	[34mINFO[0m	operator wallet: 0xa7******** (wallet)
panic: invalid page type: 2: 10 [recovered]
	panic: invalid page type: 2: 10

goroutine 1 [running]:
gopkg.in/spacemonkeygo/monkit%2ev2.newSpan.func1(0xc0001f0040)
	/go/pkg/mod/gopkg.in/spacemonkeygo/monkit.v2@v2.0.0-20190612171030-cf5a9e6f8fd2/ctx17.go:150 +0x366
panic(0xd47720, 0xc0001292b0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/boltdb/bolt.(*Cursor).search(0xc00018caa0, 0xc0000abe20, 0x8, 0x8, 0x2)
	/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/cursor.go:256 +0x354
github.com/boltdb/bolt.(*Cursor).seek(0xc00018caa0, 0xc0000abe20, 0x8, 0x8, 0x18, 0xc000362e60, 0x0, 0x0, 0xc000056a80, 0x7fbd16c696d0, ...)
	/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/cursor.go:159 +0x7e
github.com/boltdb/bolt.(*Bucket).CreateBucket(0xc0000b2718, 0xc0000abe20, 0x8, 0x8, 0xeb7f05, 0x8, 0x8)
	/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/bucket.go:172 +0xf0
github.com/boltdb/bolt.(*Bucket).CreateBucketIfNotExists(0xc0000b2718, 0xc0000abe20, 0x8, 0x8, 0x8, 0x8, 0x43079f)
	/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/bucket.go:206 +0x4d
github.com/boltdb/bolt.(*Tx).CreateBucketIfNotExists(...)
	/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/tx.go:115
storj.io/storj/storage/boltdb.NewShared.func1(0xc0000b2700, 0xeefdc0, 0xc0000b2700)
	/go/src/storj.io/storj/storage/boltdb/client.go:77 +0xab
github.com/boltdb/bolt.(*DB).Update(0xc00011a5a0, 0xc00018cd70, 0x0, 0x0)
	/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/db.go:598 +0x90
storj.io/storj/storage/boltdb.NewShared(0xc000037500, 0xf, 0xc00018ce80, 0x3, 0x3, 0x16, 0xc00018ceb0, 0xc04ae8, 0xc00018ce20, 0x2)
	/go/src/storj.io/storj/storage/boltdb/client.go:75 +0x136
storj.io/storj/storagenode/storagenodedb.New(0xc0000aef60, 0xc000037660, 0xe, 0xc0000cf000, 0x1c, 0xc0000cf020, 0x16, 0xc000037500, 0xf, 0xc000037660, ...)
	/go/src/storj.io/storj/storagenode/storagenodedb/database.go:114 +0x11c
main.cmdRun(0x18d7220, 0xc0001ba480, 0x0, 0xc, 0x0, 0x0)
	/go/src/storj.io/storj/cmd/storagenode/main.go:134 +0x39d
storj.io/storj/pkg/process.cleanup.func1.2(0xfff2c0, 0xc0001eba40)
	/go/src/storj.io/storj/pkg/process/exec_conf.go:262 +0x103
storj.io/storj/pkg/process.cleanup.func1(0x18d7220, 0xc0001ba480, 0x0, 0xc, 0x0, 0x0)
	/go/src/storj.io/storj/pkg/process/exec_conf.go:280 +0x1918
github.com/spf13/cobra.(*Command).execute(0x18d7220, 0xc0001ba3c0, 0xc, 0xc, 0x18d7220, 0xc0001ba3c0)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0x18d6fc0, 0xc0000ae120, 0x1, 0x1)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
storj.io/storj/pkg/process.Exec(0x18d6fc0)
	/go/src/storj.io/storj/pkg/process/exec_conf.go:72 +0x180
main.main()
	/go/src/storj.io/storj/cmd/storagenode/main.go:296 +0x2d
```

My docker command line

```
docker run -d --restart unless-stopped -p 28967:28967 \
    -e WALLET="<my wallet>" \
    -e EMAIL="<my email>" \
    -e ADDRESS="<external domain>:28967" \
    -e BANDWIDTH="40TB" \
    -e STORAGE="2TB" \
    --mount type=bind,source="/mnt/media/backups/identity",destination=/app/identity \
    --mount type=bind,source="/mnt/media/storj",destination=/app/config \
    --name storagenode storjlabs/storagenode:beta
```

Portforwarded 28967 on my pfSense router.

Storjnode just reboots constantly with the error message above printing over and over.

**Comment by KeirDavis1** [comment]
I'm also using a mounted NAS folder which is mounted with CIFS?

**Comment by ifraixedes** [comment]
My understanding is that `/mnt/media/storj` is a CIFS partition and CIFS filesystem doesn't support fsync or mmap and boltdb needs them.

Could you try to run your Storage Node on a local disk partition and see if you get the same problem?

**Comment by jtolio** [comment]
closing due to inactivity
