### ISSUE TITLE
[storagenode] The storagenode will panic on issue API key if databases in a separate location

### ISSUE THREAD

**Issue by AlexeyALeonov** [storj/storj#4207]
```
$ docker exec -it storagenode2 ./storagenode issue-apikey --config-dir config --identity-dir identity
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0xe959a8]

goroutine 1 [running]:
github.com/spacemonkeygo/monkit/v3.newSpan.func1(0xc00038d520)
        /go/pkg/mod/github.com/spacemonkeygo/monkit/v3@v3.0.14/ctx.go:147 +0x3bb
panic(0x10baae0, 0x19d1f80)
        /usr/local/go/src/runtime/panic.go:975 +0x47a
github.com/spacemonkeygo/monkit/v3.newSpan.func1(0xc0005b6e10)
        /go/pkg/mod/github.com/spacemonkeygo/monkit/v3@v3.0.14/ctx.go:147 +0x3bb
panic(0x10baae0, 0x19d1f80)
        /usr/local/go/src/runtime/panic.go:975 +0x47a
github.com/spacemonkeygo/monkit/v3.newSpan.func1(0xc0005b6e40)
        /go/pkg/mod/github.com/spacemonkeygo/monkit/v3@v3.0.14/ctx.go:147 +0x3bb
panic(0x10baae0, 0x19d1f80)
        /usr/local/go/src/runtime/panic.go:975 +0x47a
storj.io/storj/storagenode/storagenodedb.(*apiKeysDB).Store(0xc0005b6b50, 0x1389fc0, 0xc0004c8140, 0x17caa46c81f475da, 0xdd36bb235f61871, 0xc40aa10c5d82e18a, 0x513f8c67ab780204, 0x10eb3f93, 0xed8df8065, 0x0, ...)
        /go/src/storj.io/storj/storagenode/storagenodedb/apikeys.go:40 +0x248
storj.io/storj/storagenode/apikeys.(*Service).Issue(0xc00063eb90, 0x1389a80, 0xc00003e4c0, 0x17caa46c81f475da, 0xdd36bb235f61871, 0xc40aa10c5d82e18a, 0x513f8c67ab780204, 0x10eb3f93, 0xed8df8065, 0x0, ...)
        /go/src/storj.io/storj/storagenode/apikeys/service.go:46 +0x373
main.cmdIssue(0x19df400, 0xc00011bb80, 0x0, 0x4, 0x0, 0x0)
        /go/src/storj.io/storj/cmd/storagenode/main.go:317 +0x4c5
storj.io/private/process.cleanup.func1.4(0x1389fc0, 0xc0004c80a0)
        /go/pkg/mod/storj.io/private@v0.0.0-20210625132526-af46b647eda5/process/exec_conf.go:363 +0x11a
storj.io/private/process.cleanup.func1(0x19df400, 0xc00011bb80, 0x0, 0x4, 0x0, 0x0)
        /go/pkg/mod/storj.io/private@v0.0.0-20210625132526-af46b647eda5/process/exec_conf.go:381 +0x1fef
github.com/spf13/cobra.(*Command).execute(0x19df400, 0xc00011bb40, 0x4, 0x4, 0x19df400, 0xc00011bb40)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0x19de000, 0xc000032200, 0x127aaf8, 0x1)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
storj.io/private/process.ExecWithCustomConfig(0x19de000, 0x0, 0x127aaf8)
        /go/pkg/mod/storj.io/private@v0.0.0-20210625132526-af46b647eda5/process/exec_conf.go:88 +0x178
storj.io/private/process.ExecCustomDebug(...)
        /go/pkg/mod/storj.io/private@v0.0.0-20210625132526-af46b647eda5/process/exec_conf.go:70
main.main()
        /go/src/storj.io/storj/cmd/storagenode/main.go:385 +0x3e
```
If I would move databases back to the data location, the error is gone.

**Comment by AlexeyALeonov** [comment]
Figured it out. This is a user error - the binding was from a wrong location.
