### ISSUE TITLE
Fatal error: unexpected signal during runtime execution SIGBUS

### ISSUE THREAD

**Issue by dusselmann** [storj/storj#4378]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

I am experiening SIGBUS issues with Docker desktop on my MacOS / Mini M1. As the Mac is pretty new, I do not assume memory issues - but will verify additionally. I've opened a post in the forum already: [here](https://forum.storj.io/t/fatal-error-unexpected-signal-during-runtime-execution/16837)

I am wondering, if that could be an issue within storj code in combination with docker on M1 macs. Restarting docker each time unlocks the "freezes" storage node and everything is working again. Also, no other errors or fatals are logged into the docker logs for the storagenode. 

**Steps to reproduce the issue:**
1. Mac with Monterey OS and Docker desktop for MacOS
2. storage node up and running
3. between 1-5 days, the issue occurs

**Describe the results you expected:**
Expected that the node keeps running smoothly.

**Describe the results you received:**
Huge error log entries (will attach it here), storage node stops working. 
[storj.log](https://github.com/storj/storj/files/7887749/storj.log)

**Logs:**
Excerpt:
```
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
[signal SIGBUS: bus error code=0x2 addr=0xffff96854000 pc=0xd36f84]

runtime stack:
runtime.throw({0xfca990, 0x2a})
	/usr/local/go/src/runtime/panic.go:1198 +0x54
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:719 +0x230

goroutine 432288 [syscall]:
runtime.cgocall(0xce7fa0, 0x4002ffe6d8)
	/usr/local/go/src/runtime/cgocall.go:156 +0x50 fp=0x4002ffe690 sp=0x4002ffe650 pc=0x4034b0
github.com/mattn/go-sqlite3._Cfunc__sqlite3_step_row_internal(0xffff96739878, 0x4003d49330, 0x4003d49338)
	_cgo_gotypes.go:367 +0x44 fp=0x4002ffe6d0 sp=0x4002ffe690 pc=0xc6a9f4
github.com/mattn/go-sqlite3.(*SQLiteStmt).execSync.func3(0x4000a7a6c0, 0x4003d49330, 0x4003d49338)
	/go/pkg/mod/github.com/mattn/go-sqlite3@v1.14.8/sqlite3.go:1999 +0x68 fp=0x4002ffe710 sp=0x4002ffe6d0 pc=0xc7d628
github.com/mattn/go-sqlite3.(*SQLiteStmt).execSync(0x4000a7a6c0, {0x4005200dc0, 0x4, 0x4})
...
```

**Your environment**
- Operating system and version: 
```
System Version: macOS 12.1 (21C52)
      Kernel Version: Darwin 21.2.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: xxx
      User Name: xxx
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled

Hardware Overview:
  Model Name:	Mac mini
  Model Identifier:	Macmini9,1
  Chip:	Apple M1
  Total Number of Cores:	8 (4 performance and 4 efficiency)
  Memory:	8 GB
  System Firmware Version:	7429.61.2
  OS Loader Version:	7429.61.2
  Serial Number (system):	C07FF20JQ6NV
  Hardware UUID:	xxx
  Provisioning UDID:	xxx
  Activation Lock Status:	Enabled
```
- Additional environment details (Raspberry PI, Docker, VMWare, etc.):
`Docker version 20.10.12, build e91ed57`

**Comment by dusselmann** [comment]
Yes, they struggled yesterday morning and today morning; before that it was running without problems for about 3 days or so.

**Comment by dusselmann** [comment]
I've written a short bash script which checks each 3 mins the logs and automatically restarts docker, when number of results count > 0: 

```
$(docker logs --since 3h storagenode 2>&1 |  \
  grep -e 'unexpected shutdown' -e 'fatal error' -e 'transport endpoint is not connected' | \
  grep -v -e 'emptying trash failed' -c)
```

It runs successfully last night around 2:30 am. ;-)

Also, I am attaching a new, complete log, until the restart has taken place. Hope it helps. 
[storj2.txt](https://github.com/storj/storj/files/7900618/storj2.txt)

**Comment by dusselmann** [comment]
it’s probably a GO language dependency to sqlite @stefanbenten @littleskunk 

I've installed sqlite 3.37.2 from latest brew version instead of 3.26.x from MacOS. No change, crashed 3 times today...
