### ISSUE TITLE
'invalid memory address or nil pointer dereference' on start up

### ISSUE THREAD

**Issue by pix64** [storj/storj#4980]
**Description**

Storj crashes upon start up

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xe3c5d4]

goroutine 1 [running]:
github.com/spacemonkeygo/monkit/v3.newSpan.func1(0xc000410ec0)
        /go/pkg/mod/github.com/spacemonkeygo/monkit/v3@v3.0.17/ctx.go:147 +0x30e
panic({0x166ef80, 0x1589260})
        /usr/local/go/src/runtime/panic.go:1047 +0x266
go.uber.org/zap.(*Logger).clone(...)
        /go/pkg/mod/go.uber.org/zap@v1.16.0/logger.go:253
go.uber.org/zap.(*Logger).With(0x0, {0xc00006c000, 0x19e29c8, 0x1})
        /go/pkg/mod/go.uber.org/zap@v1.16.0/logger.go:164 +0x54
main.main.func1(0x17a8c6a)
        /go/src/storj.io/storj/cmd/storagenode/main.go:476 +0xe5
storj.io/private/process.cleanup.func1(0x1596320, {0xc0000915c0, 0x0, 0x2})
        /go/pkg/mod/storj.io/private@v0.0.0-20220614154538-e18b72a55f43/process/exec_conf.go:276 +0x882
github.com/spf13/cobra.(*Command).execute(0x1596320, {0xc0000915a0, 0x2, 0x2})
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0x15956a0)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
storj.io/private/process.ExecWithCustomConfigAndLogger(0x15956a0, 0xc0, 0x10160fba0, 0xc000052000)
        /go/pkg/mod/storj.io/private@v0.0.0-20220614154538-e18b72a55f43/process/exec_conf.go:93 +0x189
main.main()
        /go/src/storj.io/storj/cmd/storagenode/main.go:479 +0x45
````

```
2022-07-14T23:16:30.668-0400    INFO    Configuration loaded    {"Process": "storagenode", "Location": "C:\\Program Files\\Storj\\Storage Node\\config.yaml"}
Release build
Version: v1.58.2
Build timestamp: 05 Jul 22 08:40 EDT
Git commit: f8fc629f12b265792349f37a49af4ed8362caf82
```

**Steps to reproduce the issue:**

1. Start storagenode.exe with run, info or config options

**Your environment**

Windows 10 21H2 19044.1826 w/ cumulative update KB5015807

**Comment by pix64** [comment]
Performed system restore prior to Windows Update. Issue no longer reproducible.

**Comment by adaRn** [comment]
What was the Windows version prior to update?
I understand `Windows 10 21H2 19044.1826 w/ cumulative update KB5015807` is the one you're experiencing this problem on.

**Comment by pix64** [comment]
- The update which was reverted by the System Restore has automatically reinstalled and Storj continues to work.
- Storj is running the same version as previously (v1.58.2)
- config.yaml was not modified

Very unusual, but I believe this issue can be closed.

**Comment by adaRn** [comment]
That's good to hear! Feel free to re-open the issue if you find yourself experiencing the problem again.
