### ISSUE TITLE
uplink runs out of memory

### ISSUE THREAD

**Issue by damian123** [storj/storj#5997]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
-->

uplink runs out of memory 

**Screenshots**

**Steps to reproduce the issue:**
Open a command prompt and run
uplink cp --recursive y:\backup\i7 sj://backup/backup

**Describe the results you expected:**
The cp would work without any errors and the files would be copied from my local drive to storj

**Describe the results you received:**
I got an error:
runtime: VirtualAlloc of 25821184 bytes failed with errno=1455
fatal error: out of memory

**Possible Fix**
Is there anything I can do on my hyper-v settings to give it more memory or swap disk space?

**Additional information you deem important (e.g. issue happens only occasionally):**

**Logs:**

```
runtime: VirtualAlloc of 25821184 bytes failed with errno=1455
fatal error: out of memory

runtime stack:
runtime.throw({0xa46d0e?, 0xc04f61d000?})
	/usr/local/go/src/runtime/panic.go:1047 +0x65 fp=0x8439ffcb0 sp=0x8439ffc80 pc=0x2b84a5
runtime.sysUsedOS(0xc04dda2000, 0x18a0000)
	/usr/local/go/src/runtime/mem_windows.go:83 +0x1c5 fp=0x8439ffd10 sp=0x8439ffcb0 pc=0x298925
runtime.sysUsed(0xffd0a0?, 0x1703207c700?, 0x8439f0100?)
	/usr/local/go/src/runtime/mem.go:77 +0x25 fp=0x8439ffd30 sp=0x8439ffd10 pc=0x298425
runtime.(*mheap).allocSpan(0xffd0a0, 0xc50, 0x0, 0x51?)
	/usr/local/go/src/runtime/mheap.go:1340 +0x455 fp=0x8439ffdc8 sp=0x8439ffd30 pc=0x2a8855
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:961 +0x65 fp=0x8439ffe10 sp=0x8439ffdc8 pc=0x2a8025
runtime.systemstack()
	/usr/local/go/src/runtime/asm_amd64.s:496 +0x48 fp=0x8439ffe18 sp=0x8439ffe10 pc=0x2e9588

goroutine 52 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:463 fp=0xc003a75268 sp=0xc003a75260 pc=0x2e9520
runtime.(*mheap).alloc(0x18a0000?, 0xc50?, 0x8f?)
	/usr/local/go/src/runtime/mheap.go:955 +0x65 fp=0xc003a752b0 sp=0xc003a75268 pc=0x2a7f65
runtime.(*mcache).allocLarge(0xc00005cc00?, 0x18a0000, 0x1)
	/usr/local/go/src/runtime/mcache.go:234 +0x85 fp=0xc003a752f8 sp=0xc003a752b0 pc=0x297605
runtime.mallocgc(0x18a0000, 0x0, 0x0)
	/usr/local/go/src/runtime/malloc.go:1053 +0x4f7 fp=0xc003a75360 sp=0xc003a752f8 pc=0x28e297
runtime.growslice(0xc0426e4000, 0xc003a75410?, 0x10000006fdf54?, 0x13b2500?, 0x8bed29b20cb801?)
	/usr/local/go/src/runtime/slice.go:266 +0x4a8 fp=0xc003a753c0 sp=0xc003a75360 pc=0x2cdb88
storj.io/uplink/private/storage/streams/buffer.(*MemoryBackend).Write(0xc000bb5260, {0xc0069eec00, 0x1000, 0x0?})
	/go/pkg/mod/storj.io/uplink@v1.10.1-0.20230524150903-9e61c35f248e/private/storage/streams/buffer/backend.go:41 +0xb1 fp=0xc003a75420 sp=0xc003a753c0 pc=0x6fc871
storj.io/uplink/private/storage/streams/buffer.(*Buffer).Write(0xc005f69620, {0xc0069ee000?, 0x0?, 0x1d00?})
	/go/pkg/mod/storj.io/uplink@v1.10.1-0.20230524150903-9e61c35f248e/private/storage/streams/buffer/buffer.go:63 +0x166 fp=0xc003a754b8 sp=0xc003a75420 pc=0x6fcce6
storj.io/common/encryption.(*transformedWriter).Write(0xc00017bc20, {0xc0019de000?, 0xc00005cc00?, 0xa8d320?})
	/go/pkg/mod/storj.io/common@v0.0.0-20230605212838-de3bae813a7c/encryption/transform.go:237 +0x22a fp=0xc003a75548 sp=0xc003a754b8 pc=0x57ee8a
storj.io/uplink/private/storage/streams/splitter.(*encryptedBuffer).Write(0xc005f69650, {0xc0019de000?, 0xc003a75638?, 0x2fbf25?})
	/go/pkg/mod/storj.io/uplink@v1.10.1-0.20230524150903-9e61c35f248e/private/storage/streams/splitter/encrypted_buffer.go:37 +0xd0 fp=0xc003a755b8 sp=0xc003a75548 pc=0x6ff6b0
storj.io/uplink/private/storage/streams/splitter.(*baseSplitter).Write(0xc00017a240, {0xc0019de000, 0x8000, 0x8000})
	/go/pkg/mod/storj.io/uplink@v1.10.1-0.20230524150903-9e61c35f248e/private/storage/streams/splitter/base_splitter.go:96 +0x331 fp=0xc003a756f8 sp=0xc003a755b8 pc=0x6fe791
storj.io/uplink/private/storage/streams/splitter.(*Splitter).Write(...)
	/go/pkg/mod/storj.io/uplink@v1.10.1-0.20230524150903-9e61c35f248e/private/storage/streams/splitter/splitter.go:118
storj.io/uplink/private/storage/streams.(*Upload).Write(0xc000000288?, {0xc0019de000?, 0xc00011f0c0?, 0x365f80?})
	/go/pkg/mod/storj.io/uplink@v1.10.1-0.20230524150903-9e61c35f248e/private/storage/streams/upload.go:37 +0xc5 fp=0xc003a75768 sp=0xc003a756f8 pc=0x7135c5
storj.io/uplink.(*Upload).Write(0xc000000240, {0xc0019de000, 0x8000, 0x8000})
	/go/pkg/mod/storj.io/uplink@v1.10.1-0.20230524150903-9e61c35f248e/upload.go:164 +0x75 fp=0xc003a757d8 sp=0xc003a75768 pc=0x732d15
storj.io/storj/cmd/uplink/ulfs.(*uplinkWriteHandle).Write(0x29a6b2c8?, {0xc0019de000?, 0xc003a75828?, 0x3140f7?})
	/go/src/storj.io/storj/cmd/uplink/ulfs/handle_uplink.go:179 +0x25 fp=0xc003a75808 sp=0xc003a757d8 pc=0x739705
github.com/vbauerster/mpb/v8.(*nopWriteCloser).Write(0x73780d?, {0xc0019de000?, 0xc0019de000?, 0xc003a75868?})
	<autogenerated>:1 +0x2f fp=0xc003a75838 sp=0xc003a75808 pc=0x756ecf
github.com/vbauerster/mpb/v8.ewmaProxyWriter.Write({{0xb36e60?, 0xc0001b47c0?}, 0xc0001cc080?}, {0xc0019de000, 0x8000, 0x8000})
	/go/pkg/mod/github.com/vbauerster/mpb/v8@v8.4.0/proxywriter.go:36 +0x8d fp=0xc003a758a8 sp=0xc003a75838 pc=0x754acd
github.com/vbauerster/mpb/v8.(*ewmaProxyWriter).Write(0x20?, {0xc0019de000?, 0xc000008768?, 0x17030ebb0c0?})
	<autogenerated>:1 +0x49 fp=0xc003a758e8 sp=0xc003a758a8 pc=0x756aa9
io.copyBuffer({0x17030eca100, 0xc000008768}, {0xb34ea0, 0xc0015a33c0}, {0x0, 0x0, 0x0})
	/usr/local/go/src/io/io.go:429 +0x204 fp=0xc003a75968 sp=0xc003a758e8 pc=0x35c244
io.Copy(...)
	/usr/local/go/src/io/io.go:386
storj.io/common/sync2.Copy({0xb3a9b0, 0xc00006d310}, {0x17030eca100, 0xc000008768}, {0x17030eca120?, 0xc00017a2d0})
	/go/pkg/mod/storj.io/common@v0.0.0-20230605212838-de3bae813a7c/sync2/copy.go:22 +0x1f3 fp=0xc003a75a30 sp=0xc003a75968 pc=0x6c3ab3
main.(*cmdCp).copy(0x2?, {0xb3ada0?, 0xc000071e00?}, {{0x0, 0x0}, {0xc001541540, 0x48}, 0x0}, {{0xc0000300f5, 0x6}, ...}, ...)
	/go/src/storj.io/storj/cmd/uplink/cmd_cp.go:467 +0x41d fp=0xc003a75c00 sp=0xc003a75a30 pc=0x8bcb3d
main.(*cmdCp).copyFile(0xc0000000c0, {0xb3ada0, 0xc000071e00}, {0xb3e3a8, 0xc0001d6220}, {{0x0, 0x0}, {0xc001541540, 0x48}, 0x0}, ...)
	/go/src/storj.io/storj/cmd/uplink/cmd_cp.go:396 +0x525 fp=0xc003a75dd0 sp=0xc003a75c00 pc=0x8bc205
main.(*cmdCp).copyRecursive.func4()
	/go/src/storj.io/storj/cmd/uplink/cmd_cp.go:341 +0x470 fp=0xc003a75fb0 sp=0xc003a75dd0 pc=0x8bb3f0
storj.io/common/sync2.(*Limiter).Go.func1()
	/go/pkg/mod/storj.io/common@v0.0.0-20230605212838-de3bae813a7c/sync2/limiter.go:49 +0x5b fp=0xc003a75fe0 sp=0xc003a75fb0 pc=0x6c423b
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc003a75fe8 sp=0xc003a75fe0 pc=0x2eb801
created by storj.io/common/sync2.(*Limiter).Go
	/go/pkg/mod/storj.io/common@v0.0.0-20230605212838-de3bae813a7c/sync2/limiter.go:47 +0x16f
```

**Your environment**

- Operating system and version: Windows 11 Pro v. 21996.1
- Additional environment details (Raspberry PI, Docker, VMWare, etc.): Running in Hyper-V

**Comment by damian123** [comment]
>uplink version
Release build
Version:            v1.80.10
Build timestamp:    07 Jun 23 02:40 JST
Git commit:         06b61d0f1930479141b9cc207c7f1c446c7b0e3b

PATH                      VERSION
storj.io/storj            (devel)
storj.io/common           v0.0.0-20230605212838-de3bae813a7c
storj.io/drpc             v0.0.33
storj.io/monkit-jaeger    v0.0.0-20220915074555-d100d7589f41
storj.io/picobuf          v0.0.1
storj.io/private          v0.0.0-20230405095015-9e5bbc1c7ca8
storj.io/uplink           v1.10.1-0.20230524150903-9e61c35f248e

**Comment by Th3Van** [comment]
Could be related, but i don't know if the fix has been released yet.

https://forum.storj.io/t/upload-refactoring/22559/27

Th3Van.dk
