### ISSUE TITLE
Add linting step to Jenkins for API generator

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6678]
Currently, attempting to generate the console generated API on the main branch results in the following error:
```
$ go generate ./satellite/console/...
panic: duplicated field name for TypeScript class. Go embedded struct fields are only accepted if their JSON field name is unique across all the fields that flatten into the parent struct. Found duplicated on (console.APIKeyInfo).Secret (json name: )

goroutine 1 [running]:
storj.io/storj/private/apigen.GetClassFieldsFromStruct.func1({0xd86ec8, 0xc4c7e0})
        /home/moby/dev/storj/storj/private/apigen/tstypes.go:287 +0x614
storj.io/storj/private/apigen.GetClassFieldsFromStruct({0xd86ec8, 0xc4c7e0})
        /home/moby/dev/storj/storj/private/apigen/tstypes.go:316 +0xca
storj.io/storj/private/apigen.(*Types).GenerateTypescriptDefinitions.func2(0xc0002a3100, 0xc0002a30f0)
        /home/moby/dev/storj/storj/private/apigen/tstypes.go:147 +0x112
storj.io/storj/private/apigen.(*Types).GenerateTypescriptDefinitions(0xc0002a3240?)
        /home/moby/dev/storj/storj/private/apigen/tstypes.go:151 +0xca
storj.io/storj/private/apigen.(*tsGenFile).generateTS(0xc0002a3240)
        /home/moby/dev/storj/storj/private/apigen/tsgen.go:61 +0x213
storj.io/storj/private/apigen.(*API).MustWriteTS(0xc000177400, {0xc00024d340, 0x3a})
        /home/moby/dev/storj/storj/private/apigen/tsgen.go:22 +0x66
main.main()
        /home/moby/dev/storj/storj/satellite/console/consoleweb/consoleapi/gen/main.go:163 +0x1b3d
exit status 2
satellite/console/consoleweb/consoleapi/gen/main.go:6: running "go": exit status 1
```

The reason this was introduced was most likely that we made API generator changes for satellite/admin/back-office which were not executed against the console generated API. We need a Jenkins test that prevents merge in a situation where APIs were not regenerated with the latest apigen code. This is similar to our `satellite/configlock_test.go`, which fails in a situation where satellite configs are modified, but `satellite/satellite-config.yaml.lock` is not updated.

## AC:
* update satellite/console/consoleweb/consoleapi/gen so that `go generate ./satellite/console/...` correctly generates API files again
* add a test which fails if there is any difference between the files before and after the following APIs are generated:
  * `satellite/console/consoleweb/consoleapi/gen/main.go`
  * `satellite/admin/back-office/gen/main.go`
  * `private/apigen/example/gen.go`

**Comment by ifraixedes** [comment]
We already tracked this in #6479.
I'm closing #6479 as duplicated in favor of this one.
